# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutoChek' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SOTabBar' 
  pod 'Alamofire', '~> 5.2'
  pod 'SDWebImage', '~> 5.0'
  pod 'SDWebImageSVGCoder'
  pod 'JGProgressHUD'
  # Pods for AutoChek

end
